pagopa/pagopa-api-config

- .devops/code-review-pipelines.yml
- pom.xml
- src/main/java/it/pagopa/pagopa/apiconfig/config/RetryableDatabasePostProcessor.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsService.java
The purpose of this PR is to create a pipeline on azure for code review
- added code-review pipeline file
- set jdk version to 11 in pom file ([Azure not support version 16](https://docs.microsoft.com/it-it/azure/devops/pipelines/tasks/build/maven?view=azure-devops))
To monitor the code quality
> [PCFG-14] added code-review pipeline and set jdk version to 11

- .devops/code-review-pipelines.yml
- openapi/swagger.yaml
- src/main/java/it/pagopa/pagopa/apiconfig/config/MappingsConfiguration.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/CreditorInstitutionsController.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/Pa.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/PaStazionePa.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/Stazioni.java
- src/main/java/it/pagopa/pagopa/apiconfig/exception/AppException.java
- src/main/java/it/pagopa/pagopa/apiconfig/exception/ErrorHandler.java
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertPaToCreditorInstitution.java
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertStazioniToStation.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/CreditorInstitution.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/Station.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/PaRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/PaStazionePaRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/StazioniRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsService.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/CreditorInstitutionsControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/exception/ErrorHandlerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsServiceTest.java
- src/test/resources/application.properties
- src/test/resources/response/get_creditorinstitution_ok.json
- src/test/resources/response/get_creditorinstitutions_ok1.json
- src/test/resources/response/get_creditorinstitutions_ok2.json
The purpose of this PR is add a new service to retrieve detail of a CE
- implemented: GET `/creditorinstitutions/{organizationfiscalcode}`
- modified CE controller
- modified CE service
- new entities and repository
To implement a  new feature
Unit tests added
> [PCFG-9] implemented details of a CE

- .devops/azure-templates/maven-versioning.yml
- .devops/azure-templates/setup-project.yml
- .devops/deploy-pipelines.yml
- pom.xml
- src/main/java/it/pagopa/pagopa/apiconfig/controller/HomeController.java
- src/main/resources/application-azure-temp.properties
- src/main/resources/application-docker.properties
- src/main/resources/application-local.properties
- src/main/resources/application.properties
- added `deploy-pipeline.yml`
- added `maven-versioning.yml`
- added **health check:** new endpoint GET `/info`
This PR adds a pipeline that creates a release on Github and releases the package on Azure
> [PCFG-39] added deploy pipeline file

- README.md
> [PCFG-47] automation

- .github/release.yml
- api-test/ApiConfig.postman_collection.json
- openapi/openapi.json
- src/main/java/it/pagopa/pagopa/apiconfig/config/MappingsConfiguration.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/IcaController.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/BinaryFile.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/InformativeContoAccreditoMaster.java
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertInformativeContoAccreditoMasterRepositoryToIca.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/Ica.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/Icas.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/InformativeContoAccreditoMasterRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/IcaService.java
- src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/IcaControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/IcaServiceTest.java
- src/test/resources/response/get_icas_ok.json
Implemented GET `/icas`
Implemented GET `/icas/{idica}`
- implemented business logic in `IcasService.java`
- added entities for ICA
To introduce new features
added Junit tests
> [PCFG-28] ica

- api-test/ApiConfig.postman_collection.json
- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/config/MappingsConfiguration.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/CreditorInstitutionsController.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/IntermediariPa.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/Pa.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/PaStazionePa.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/Stazioni.java
- src/main/java/it/pagopa/pagopa/apiconfig/exception/AppError.java
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertCreditorInstitutionStationPostToPaStazionePa.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/CreditorInstitutionDetails.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/CreditorInstitutionStationEdit.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/PaStazionePaRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsService.java
- src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/CreditorInstitutionsControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsServiceTest.java
- src/test/resources/response/create_creditorinstitution_stations_ok1.json
- src/test/resources/response/update_creditorinstitution_stations_ok1.json
Implemented POST `/creditorinstitutions/:code/stations` 
Implemented PUT `/creditorinstitutions/:code/stations/:stationcode`
Implemented DELETE `/creditorinstitutions/:code/stations/:stationcode`
- updated CreditorInstitutionsController.java
- added new endpoints
- updated CreditorInstitutionsService.java
- implemented business logic
- updated swagger and postman collection
- added new errors into AppError.java enum
To introduce the following features : 
- [createCreditorInstitutionStations](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/374375153/Design+Review+API+configurazione+pagoPA#createCreditorInstitutionStations)
- [updateCreditorInstitutionStations](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/374375153/Design+Review+API+configurazione+pagoPA#updateCreditorInstitutionSta …
> [PCFG-76] implemented relation Station-CI

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertPaToCreditorInstitutionDetails.java
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertToCreditorInstitutionDetailsToPa.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/CreditorInstitutionDetails.java
- src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
removed fk_quadrature from `POST /creditorinstitutions `
The field is useless for now
> [PCFG-80] removed fk quadrature

- src/main/java/it/pagopa/pagopa/apiconfig/config/WebMvcConfiguration.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/BrokerController.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/BrokerPspController.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/CounterpartController.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/CreditorInstitutionsController.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/EncodingsController.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/HomeController.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/IcaController.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/PspController.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/StationsController.java
- src/main/java/it/pagopa/pagopa/apiconfig/exception/ErrorHandler.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/AppCorsConfiguration.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/ProblemJson.java
- src/main/resources/application-azure-d.properties
- src/main/resources/application-azure-p.properties
- src/main/resources/application-azure-t.properties
- src/main/resources/application-azure-u.properties
- src/main/resources/application-h2.properties
- src/main/resources/application.properties
- src/main/resources/logback.xml
- src/test/java/it/pagopa/pagopa/apiconfig/exception/ErrorHandlerTest.java
- added CORS configuration in application.properties
- added model
The application read the CORS configuration from environment. The environment is set in the `pagopa-infra `repository.
manually
> CORS Configuration

- api-test/ApiConfig.postman_collection.json
- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/controller/IcaController.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/InformativeContoAccreditoMasterRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/IcaService.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/IcaControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/IcaServiceTest.java
- updated IcaController.java
- added new parameter
- updated IcaService.java
- added new parameter
- updated query in the Repository
- updated doc
- updated tests
To fix a bug. 
`IcaId` and `creditorInstitutionCode` identify a ICA
- manually
- junit test
> [Bugfix] Added creditorinstitution parameter on GET `/icas`  

- CODEOWNERS
- api-test/setup_env_api_test.sh
Fix `setup_env_api_test.sh` 
- Handled case: `t (test)`
> fix script

- api-test/setup_env_api_test.sh
> Fix setup env

- pom.xml
- src/main/java/it/pagopa/pagopa/apiconfig/config/RequestFilter.java
- src/main/java/it/pagopa/pagopa/apiconfig/config/WebMvcConfiguration.java
- bugfix Log4J
- enchantment requestId
> [PCFG-100] Upgrade Log4j version

- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertPaToCreditorInstitution.java
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertPspToPaymentServiceProvider.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/psp/PaymentServiceProvider.java
The purpose of this PR is to fix unwanted `Left` response type on auto-generate client `getPaymentServiceProviders`.
> fix correct value type for psp and pa business_name

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/entity/CdiMaster.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/InformativePaMaster.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/Psp.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/psp/PaymentServiceProviderDetails.java
- src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
- src/test/resources/response/get_paymentserviceprovider_ok.json
> [FIX] switch long flag to boolean

- api-test/ApiConfig.postman_collection.json
- openapi/openapi.json
- openapi/swagger.json
- pom.xml
- src/main/java/it/pagopa/pagopa/apiconfig/config/MappingsConfiguration.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/BrokerPspController.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/IntermediariPsp.java
- src/main/java/it/pagopa/pagopa/apiconfig/exception/AppError.java
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertBrokerPspDetailsToIntermediariPsp.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/BrokersPspService.java
- src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/BrokerPspControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/BrokersPspServiceTest.java
- src/test/resources/response/create_brokerpsp_ok.json
- src/test/resources/response/update_brokerpsp_ok.json
- POST `/brokerspsp`
- PUT `/brokerspsp/{brokerpspcode}`
- DELETE `/brokerspsp/{brokerpspcode}`
- Updated `BrokerPspController.java`
- added Post Put and Delete services
- Updated `BrokerPspService.java`
- implemented Post Put and Delete services
- Updated Postman Collection
- Updated OpenApi.json
- Added explicit hibernate dependency to set the last version because it needs the `@Type` annotation
To add new services for the resource broker PSP
- Junit tests
- manually
> [PCFG-92] C/D/U BrokerPsp

- src/main/java/it/pagopa/pagopa/apiconfig/controller/HomeController.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/AppInfo.java
> App info in the health check

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/config/SwaggerConfig.java
- Modified Bearer to lower case
> Fix swagger

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/entity/ElencoServizi.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/IntermediariPa.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/Pa.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/PaStazionePa.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/Psp.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/Stazioni.java
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertCreditorInstitutionStationPostToPaStazionePa.java
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertStationDetailsToStazioni.java
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertStazioniToStationDetails.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/Broker.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/CounterpartTable.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/CreditorInstitution.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/Ica.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/PageInfo.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/StationDetails.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/XSDValidation.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/PaStazionePaRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/StazioniRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsService.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/StationsService.java
- src/main/resources/application-local.properties
- src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/IcaControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsServiceTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/StationsServiceTest.java
- fix create station
- fix query to get  the list of stations
- refactor swagger
- fix boolean in the entities (from number 0/1 to char Y/N)
> [PCFG-138][PCFG-139] Bug Fix

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/exception/AppError.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/psp/ChannelDetails.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/psp/PspChannelPaymentTypes.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/ChannelsService.java
- src/main/java/it/pagopa/pagopa/apiconfig/util/CommonUtil.java
- src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/ChannelsControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/ChannelsServiceTest.java
- src/test/resources/response/create_psp_channels_ok.json
- src/test/resources/response/get_paymenttype_ok1.json
- src/test/resources/response/get_psp_channels_ok1.json
- src/test/resources/response/update_psp_channels_ok.json
- replace not-empty annotation with not-null one
- fix field name
- generated swagger
> Minor fix payment type

- src/main/java/it/pagopa/pagopa/apiconfig/controller/ConfigurationController.java
> method name fix

- pom.xml
- src/main/java/it/pagopa/pagopa/apiconfig/service/BrokersPspService.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/BrokersService.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/CdiService.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/ChannelsService.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/ConfigurationService.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/CounterpartService.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsService.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/EncodingsService.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/IcaService.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/PspService.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/ServicesService.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/StationsService.java
- updated dependencies in POM
- added @Validated to all @Services
> Updated Dependencies

- .devops/azure-templates/maven-versioning.yml
- .devops/deploy-pipelines.yml
- pom.xml
- src/main/java/it/pagopa/pagopa/apiconfig/config/LoggingAspect.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/AppInfo.java
- src/main/resources/application-azure-d.properties
- src/main/resources/application-azure-u.properties
- added execution time log
- added build number option: this option create a new version in the pom using `-` as separator (example: 5.0.0-1)
> [PCFG-145] verificare il timeout su db in uat

- api-test/ApiConfig.postman_collection.json
- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/controller/IcaController.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/InformativeContoAccreditoDetail.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/InformativeContoAccreditoMaster.java
- src/main/java/it/pagopa/pagopa/apiconfig/exception/AppError.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/IcaXml.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/filterandorder/Filter.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/BinaryFileRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/InformativeContoAccreditoDetailRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/InformativeContoAccreditoMasterRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/IcaService.java
- src/main/java/it/pagopa/pagopa/apiconfig/util/CommonUtil.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/IcaControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/IcaServiceTest.java
- src/test/resources/file/ica_valid_h2.xml
- Create ICA
- Delete ICA
- updated openapi and postman collection
To add new features
- junit tests
- manually
> [PCFG-37] ICA Create and Delete

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/config/RetryableDataSource.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/HomeController.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/AppInfo.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/HealthCheckRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/HealthCheckService.java
- src/main/resources/application-azure-d.properties
- src/main/resources/application-azure-p.properties
- src/main/resources/application-azure-t.properties
- src/main/resources/application-azure-u.properties
- src/main/resources/application-docker.properties
- src/main/resources/application-h2.properties
- src/main/resources/application-local.properties
- src/main/resources/application.properties
- src/test/java/it/pagopa/pagopa/apiconfig/controller/HomeControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/HealthCheckServiceTest.java
Added info about db connection to health-check service.
- db connection status:
- "up": db connection established properly
- "down": db connection lost
> [PCFG-43] DB Connection in health-check

- api-test/ApiConfig.postman_collection.json
- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/controller/CdiController.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/CounterpartController.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/IcaController.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/CdiMasterRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/InformativeContoAccreditoMasterRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/InformativePaMasterRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/CdiService.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/CounterpartService.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/IcaService.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/CdiControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/CounterpartControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/IcaControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/CdiServiceTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/CounterpartServiceTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/IcaServiceTest.java
depends on #78 
added filters in
- GET /icas
- GET /counterpart
- GET /cdis
more details [here](https://pagopa.atlassian.net/browse/PCFG-158)
to add filters and new features
- junit test
- manually
> [PCFG-158] Filter XML

- openapi/generate_openapi_and_swagger.sh
- openapi/swagger.json
> Fix swagger generation script

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/controller/CdiController.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/CounterpartController.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/IcaController.java
- added missing 409 in the swagger definitions
to solve the problem with the autogenerated typescript client
> Fix swagger Delete XMLs

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/controller/PspController.java
- src/main/java/it/pagopa/pagopa/apiconfig/exception/AppError.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/PspService.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/PspControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/PspServiceTest.java
> [PCFG-169] PSP-Channel relationship

- .github/workflows/main.yml
- github action: auto add assignee to PR
> Github action

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertStationDetailsToStazioni.java
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertStazioniToStationDetails.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/StationDetails.java
- src/test/resources/response/get_station_ok1.json
- src/test/resources/response/update_station_ok.json
added POF service to station response
> [PCFG-177] Fix Pof Service

- src/main/java/it/pagopa/pagopa/apiconfig/config/LoggingAspect.java
- src/main/java/it/pagopa/pagopa/apiconfig/exception/ErrorHandler.java
- src/main/resources/application-azure-d.properties
- src/main/resources/application-local.properties
> Logging Improves

- .pre-commit-config.yaml
- openapi/generate_openapi_and_swagger.sh
- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/config/LoggingAspect.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/PspController.java
- src/main/java/it/pagopa/pagopa/apiconfig/exception/ErrorHandler.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/psp/ChannelDetails.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/ChannelsService.java
- src/main/resources/application-azure-d.properties
- src/main/resources/application-local.properties
- src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
- src/test/java/it/pagopa/pagopa/apiconfig/exception/ErrorHandlerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/ChannelsServiceTest.java
- src/test/resources/response/create_channel_ok.json
- src/test/resources/response/update_channel_ok.json
depends on #89 
- added pre-commit and gitguardian
- add a special error message when there is a relation with other resource. 
- fix bugs
- change log level
junit tests
manually
> [PCFG-187]

- src/main/java/it/pagopa/pagopa/apiconfig/config/LoggingAspect.java
- src/main/java/it/pagopa/pagopa/apiconfig/config/RetryableDataSource.java
- src/main/java/it/pagopa/pagopa/apiconfig/config/RetryableDatabasePostProcessor.java
- src/main/java/it/pagopa/pagopa/apiconfig/exception/ErrorHandler.java
- src/main/resources/application-azure-d.properties
- src/main/resources/application-azure-p.properties
- src/main/resources/application-azure-t.properties
- src/main/resources/application-azure-u.properties
depends on https://github.com/pagopa/pagopa-infra/pull/239
> Loging Level as env var

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/controller/StationsController.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/PaStazionePaRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/StationsService.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/StationsControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/StationsServiceTest.java
- src/test/resources/response/get_station_creditorinstitutions_ok.json
- retrieve creditor institution list of a station
> [PCFG-172] Creditor institution list of a station

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertCreditorInstitutionDetailsToPa.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/CreditorInstitutionAddress.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/CreditorInstitutionDetails.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsServiceTest.java
- src/test/resources/response/update_creditorinstitution_ok.json
- set address of creditor institution not mandatory
> [PCFG-213] CI address

- load-test/README.md
- load-test/creditor_institutions.js
- load-test/dev.environment.json.example
- load-test/helpers/authentication.js
- load-test/helpers/ci_broker_helper.js
- load-test/helpers/creditor_institutions_helper.js
- load-test/helpers/station_helper.js
- load-test/local.environment.json
- k6 script for the creditor institution section
> [PCFG-207] Creditor institution load test

- load-test/README.md
- load-test/creditor_institutions.js
- load-test/helpers/station_helper.js
- load-test/station.js
depends on https://github.com/pagopa/pagopa-api-config/pull/101
- k6 script for the statio section
> [PCFG-209] Station load test

- load-test/README.md
- load-test/ci_broker.js
- load-test/helpers/ci_broker_helper.js
depends on https://github.com/pagopa/pagopa-api-config/pull/102
- k6 script for the creditor institution broker section
> [PCFG-208] Broker load test

- load-test/helpers/creditor_institutions_helper.js
- load-test/helpers/ica_helper.js
- load-test/ica.js
- load-test/resources/ica.xml
depends on https://github.com/pagopa/pagopa-api-config/pull/103
- k6 script for the ica section
> [PCFG-210] ICA load test

- .github/workflows/check_metadata_pr.yml
- .github/workflows/update_infra.yml
- src/main/java/it/pagopa/pagopa/apiconfig/repository/PaStazionePaRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsService.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/MassiveLoadingService.java
- src/main/java/it/pagopa/pagopa/apiconfig/util/CreditorInstitutionStationVerifier.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsServiceTest.java
Added a check to unique application code and unique segregation code when you try to add a new Station-CI relation
To solve this [issue](https://pagopa.atlassian.net/browse/PCFG-221)
> [PCFG-221] BugFix unique application/segregation code 

- api-test/ApiConfig.postman_collection.json
- load-test/helpers/station_helper.js
- load-test/station.js
- src/main/java/it/pagopa/pagopa/apiconfig/controller/StationsController.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/StationsService.java
- src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/StationsControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/StationsServiceTest.java
- added api call for Station-EC relation
- new feature to check if there is a relationship between station and EC
Junit and Postman test
> [PCFG-231] ec station

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/controller/ConfigurationController.java
> [PCFG-216] Update Swagger

- src/main/java/it/pagopa/pagopa/apiconfig/service/StationsService.java
> [PCFG-233] Fix CSV Station

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/controller/IbanController.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/CreditorInstitutionList.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/IbanValidiPerPaRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsService.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/IbanControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsServiceTest.java
- src/test/resources/response/get_creditorinstitutions_by_iban_1.json
- src/test/resources/response/get_creditorinstitutions_by_iban_2.json
- find creditor institution list by iban (`equals`)
> [PCFG-214] Find creditor institution list by IBAN

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/controller/IbanController.java
> Changed method name

- api-test/ApiConfig.postman_collection.json
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/StationDetails.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/psp/ChannelDetails.java
- added default timestamp values:
- timestamp_a: 15s
- timestamp_b: 30s  
- timestamp_c: 120s
- [] New feature (non-breaking change which adds functionality)
> [PCFG-234] Added default timestamp values

- api-test/ApiConfig.postman_collection.json
- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/controller/ChannelsController.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/StationsController.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/ChannelsService.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/ChannelsControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/ChannelsServiceTest.java
GET `channels/:code/paymentserviceproviders/csv` 
to download a CSV file with PSP list of a channel
[Jira Task](https://pagopa.atlassian.net/browse/PCFG-200)
junit
> [PCFG-200] Export PSP list of a Channel

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/model/psp/Service.java
- fix openapi & swagger according to real `GET services` response:
- `logo_service` and `logo_psp` as byte string and not array of byte string;
The goal of this PR is to update  the `GET services` response in openapi and swagger file to handle `logo_service` and `logo_psp` as byte string and not array of byte string.
> fix: openapi & swagger

- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertPaymentServiceProviderDetailsToPsp.java
- set default value to false for `FLAG_REPO_COMMISSIONE_CARICO_PA`
> [PCFG-243] `FLAG_REPO_COMMISSIONE_CARICO_PA` default value

- src/main/java/it/pagopa/pagopa/apiconfig/exception/AppError.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/Broker.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/EncodingsService.java
- src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
Added check to encondings:
- QR-CODE must be 11 digits
- BARCODE-128-AIM must be 12 digits
> [PCFG-247] Encondings check

- src/main/java/it/pagopa/pagopa/apiconfig/exception/AppError.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/Encoding.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/EncodingsService.java
removed the possibility to set BARCODE_GS1_128 (deprecated)
BARCODE_GS1_128 is deprecated
> [PCFG-258] fix BARCODE_GS1_128

- README.md
- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertCanaliToChannel.java
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertCanaliToChannelDetails.java
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertChannelDetailsToCanali.java
- src/main/java/it/pagopa/pagopa/apiconfig/mapper/ConvertStazioniToStation.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/Station.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/psp/Channel.java
- src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
- src/test/resources/response/create_channel_ok.json
- src/test/resources/response/get_channel_ok1.json
- src/test/resources/response/get_channels_ok1.json
- src/test/resources/response/get_stations_ok1.json
- src/test/resources/response/update_channel_ok.json
Added Broker Description to Channels and Stations models
> [PCFG-259] Added Broker Description

- src/main/java/it/pagopa/pagopa/apiconfig/service/CounterpartService.java
- update ec field
Update PAGAMENTO_PRESSO_PSP according to info contained in the couterpart table xml 👉  https://pagopa.atlassian.net/browse/PCFG-198
> [PCFG-198] Update EC field

- src/main/java/it/pagopa/pagopa/apiconfig/model/configuration/PddBase.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/CreditorInstitutionStation.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/CreditorInstitutionStationEdit.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/StationDetails.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/psp/ChannelDetails.java
> [PCFG-274] Added check on number fields

- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/Station.java
> [PCFG-272] Check station version

- src/main/java/it/pagopa/pagopa/apiconfig/model/creditorinstitution/CsvMassiveMigration.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/MassiveLoadingService.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/MassiveLoadingServiceEserTest.java
- src/test/resources/file/massive_migration.csv
- src/test/resources/file/massive_migration_2.csv
- src/test/resources/file/massive_migration_bad.csv
> [PCFG-283] bugfix: massive migration csv converter

- src/main/java/it/pagopa/pagopa/apiconfig/controller/ConfigurationController.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/configuration/PaymentType.java
- src/test/java/it/pagopa/pagopa/apiconfig/TestUtil.java
- src/test/resources/response/create_payment_type_ok.json
Add a check to accept only UPPERCASE for paymentType
[Feedback Operation](https://pagopa.atlassian.net/browse/PCFG-271)
> Revision Payment Options

- src/main/java/it/pagopa/pagopa/apiconfig/service/IcaService.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/IcaServiceTest.java
- src/test/resources/file/ica_date_not_valid_h2.xml
- added check on format of validity date
> [PCFG-288] Add check on validity date format

- src/main/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsService.java
Update the check for Aux Digit:
- if aux digit is 3 the application code can be null
- if aux digit is 0 the segregation code can be null
to resolve a bug
junit
> [PCFG-292] Fix Bug AuxDigit

- src/main/java/it/pagopa/pagopa/apiconfig/service/MassiveLoadingService.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/MassiveLoadingServiceEserTest.java
- src/test/resources/file/massive_migration_conflict.csv
- added check on destination station.
[Jira task](https://pagopa.atlassian.net/browse/PCFG-294)
> feat: [PCFG-294] massive migration bug fix 

- openapi/generate_openapi_and_swagger.sh
- openapi/openapi.json
- openapi/swagger.json
- added fix to swagger about `icas/check`
> feat: Fix to swagger

- src/main/java/it/pagopa/pagopa/apiconfig/config/RequestFilter.java
- src/main/java/it/pagopa/pagopa/apiconfig/exception/ErrorHandler.java
small changes to logs
analysing the azure logs on app insight
> Improve Logs

- docker-compose.yaml
- src/main/java/it/pagopa/pagopa/apiconfig/repository/CodifichePaRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsService.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/CreditorInstitutionsServiceTest.java
- add QR Encoding when create a new EC
> [PCFG-251] QR Code for New EC

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/controller/IcaController.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/IcaService.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/IcaServiceTest.java
- add new parameter to force the upload of ICA file
> [PCFG-298] Add force upload to ICA

- .github/workflows/check_metadata_pr.yml
- .github/workflows/update_openapi.yml
- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/config/ResponseValidator.java
- src/main/java/it/pagopa/pagopa/apiconfig/model/psp/PaymentServiceProvider.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/PspService.java
> Improvements

- openapi/openapi.json
- openapi/swagger.json
- pom.xml
- src/main/resources/application-azure-d.properties
- src/main/resources/application-azure-p.properties
- src/main/resources/application-azure-t.properties
- src/main/resources/application-azure-u.properties
Updating application properties variables in d, u, p files
Bug fix
> Updating properties values in d, u, p

- src/main/java/it/pagopa/pagopa/apiconfig/service/StationsService.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/StationsServiceTest.java
Fixing station url inside the created csv
The fix was necessary to fix the generated url
This has been tested using postman
> PAGOPA-111 minor fix adding path part

- src/main/java/it/pagopa/pagopa/apiconfig/exception/AppError.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/CdiService.java
- src/main/resources/application-azure-d.properties
- src/main/resources/application-azure-p.properties
- src/main/resources/application-azure-t.properties
- src/main/resources/application-azure-u.properties
- src/main/resources/application-docker.properties
- src/main/resources/application-h2.properties
- src/main/resources/application-local.properties
- src/main/resources/application.properties
- src/test/java/it/pagopa/pagopa/apiconfig/service/CdiServiceTest.java
- src/test/resources/application.properties
- trigger to afm-utils for history and create cdi
> [PAGOPA-618] Trigger to AFM Utils

- src/main/java/it/pagopa/pagopa/apiconfig/cosmos/container/CdiCosmos.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/CdiService.java
- added the ABI value from PSP to CDI
- the marketplace bundle needs of ABI info
Manual and junit test
> [PAGOPA-633] abi cdi: added ABI in CDI object

- api-test/ApiConfig.postman_collection.json
- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/pagopa/pagopa/apiconfig/controller/BrokerPspController.java
- src/main/java/it/pagopa/pagopa/apiconfig/controller/PspController.java
- src/main/java/it/pagopa/pagopa/apiconfig/entity/Psp.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/CanaleTipoVersamentoRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/CanaliRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/repository/PspRepository.java
- src/main/java/it/pagopa/pagopa/apiconfig/service/BrokersPspService.java
- src/test/java/it/pagopa/pagopa/apiconfig/controller/BrokerPspControllerTest.java
- src/test/java/it/pagopa/pagopa/apiconfig/service/BrokersPspServiceTest.java
- src/test/resources/response/get_psp_brokerpsp.json
- added`GET /brokerpsp/{brokerpspcode}/paymentserviceproviders`
- update `openapi.json`
- update postman collection
- junit test
- integration with self care
- manual
- junit tests
> [PAGOPA-669] Get PSP by broker code

- .devops/deploy-pipelines.yml
- .github/workflows/anchore.yml
- .github/workflows/code_review.yml
- .github/workflows/release_deploy.yml
- .github/workflows/self_hosted.yml
- .github/workflows/update_infra.yml
- .identity/.terraform.lock.hcl
- Dockerfile
- openapi/openapi.json
- openapi/openapi_auth.json
- openapi/swagger.json
- pom.xml
fix deploy pipeline
use github token to download apiconfig-starter dependency
> fix deploy pipeline

- src/main/java/it/gov/pagopa/apiconfig/core/service/CdiService.java
- src/main/java/it/gov/pagopa/apiconfig/core/util/CommonUtil.java
hotfix nullPointer when CDI is upload without codiceAbi
> [PAGOPA-971] hotfix null pointer CDI

- load-test/helpers/iban_helper.js
- load-test/ibans.js
This Pull Request contains all the updates made on performance test suite in order to execute specific tests on IBAN handle APIs.
- Updated performance tests
This update will add a test case on performance tests
> [PAGOPA-1003] update performance test including IBAN handle tests

- .gitignore
- pom.xml
> fix: Bump vers

- pom.xml
> fix: Bump version for sprint closure 

- src/main/java/it/gov/pagopa/apiconfig/core/model/creditorinstitution/IbanEnhanced.java
- src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
- src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
- src/test/java/it/gov/pagopa/apiconfig/core/scheduler/SchedulerTest.java
- src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
- POST IbanEnhanced was updated for the case of postal IBAN:
when a postal IBAN is added, an Encoding is created associated with the EC specified in the IBAN;
- DELETE Iban was updated for the case of postal IBAN:
when a postal IBAN is removed, the related Encoding is deleted if it exists;
- Input validation was modified to conform to the regexes described [here](https://raw.githubusercontent.com/pagopa/pagopa-api/SANP3.3.0/xsd/InformativaContoAccredito_1_2_1.xsd):
EC fiscal code must comply with `[0-9]{11}`
IBAN must comply with `[a-zA-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}`
- Some unit tests have been added others updated;
The updated features were tested through JUnit test.
> feat: Update IBAN Service for Encoding handling [PAGOPA-1014]

- src/main/resources/application.properties
- Add hikari test query connection to fix jdbc connection error
> [PAGOPA-1119] fix: Add hikari test query connection

- src/main/resources/application.properties
> fix: HEALTHCHECK_QUERY ora

- openapi/openapi.json
- openapi/openapi_auth.json
- openapi/swagger.json
- src/main/java/it/gov/pagopa/apiconfig/core/model/creditorinstitution/Iban.java
- src/main/java/it/gov/pagopa/apiconfig/core/service/CdiService.java
- src/main/java/it/gov/pagopa/apiconfig/core/util/AFMUtilsAsyncTask.java
- src/test/java/it/gov/pagopa/apiconfig/core/service/CdiServiceTest.java
Fixing the iban, removing the required clause to the publication date 
Refactoring iban model, removing the required and not null clauses from publication_date. In addition, description to the various fields is provided.
This fix was necessary in order for the front-end to work properly, since the release of the new view. 
This has been tested manually using the H2 profile.
> fix: refactoring iban model with publication date null PAGOPA-1149

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- src/main/java/it/gov/pagopa/apiconfig/core/controller/HomeController.java
- src/main/resources/logback-spring.xml
new jdbc string
to resolve the JDCB Connection error
> [PAGOPA-1228] new jdbc string

- .github/workflows/release_deploy.yml
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- openapi/openapi_auth.json
- openapi/swagger.json
- pom.xml
- src/main/java/it/gov/pagopa/apiconfig/core/service/RefreshService.java
- src/test/java/it/gov/pagopa/apiconfig/core/service/RefreshServiceTest.java
a fix for the response from node
> [PAGOPA-1259] fix: refresh of the cache

- openapi/openapi.json
- src/main/java/it/gov/pagopa/apiconfig/core/controller/RefreshController.java
- src/main/java/it/gov/pagopa/apiconfig/core/exception/AppError.java
- src/main/java/it/gov/pagopa/apiconfig/core/service/RefreshService.java
> [PAGOPA-1053] Feedback on refresh of the configurazione

- .gitignore
- pom.xml
- src/main/java/it/gov/pagopa/apiconfig/core/config/LoggingAspect.java
- src/main/java/it/gov/pagopa/apiconfig/core/service/CacheService.java
- src/test/java/it/gov/pagopa/apiconfig/core/service/CacheServiceTest.java
This PR add a new filter to exclude the cache versions with `GZIP_JSON` prefix
bug fixing
junit test
> [PAGOPA-1273] filter cache version

- src/main/java/it/gov/pagopa/apiconfig/core/model/creditorinstitution/CreditorInstitutionStationEdit.java
- src/main/java/it/gov/pagopa/apiconfig/core/service/CreditorInstitutionsService.java
check if auxdigit is null
bugfix
> Bugfix AuxDigit NullPointer

- .github/workflows/update_infra.yml
- Update update_infra.yml destination folder
- After `api-config-core` migration in `pagopa-infra` the OpenAPI path was changed.
> chore: Update update_infra.yml destination folder [PAGOPA-1325] 

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- integration-test/src/step_definitions/support/builder/buildIban.js
- openapi/openapi.json
- openapi/openapi_auth.json
- openapi/swagger.json
- pom.xml
- src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
- src/main/java/it/gov/pagopa/apiconfig/core/util/CommonUtil.java
- src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
Depends on [create](https://github.com/pagopa/pagopa-api-config/pull/269)
- added coding if not exist and check dates
- business request
Junit and manual test
> feat: [PAGOPA-1356] update iban with encoding

- helm/values-prod.yaml
> chore: Upd min replica

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
- src/main/java/it/gov/pagopa/apiconfig/core/controller/IbanController.java
- src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
- src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
- src/test/java/it/gov/pagopa/apiconfig/core/controller/IbanControllerTest.java
- src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
> [PASELC-634] feat: IBAN label Stand-In management and other fixes

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
- src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
- src/main/java/it/gov/pagopa/apiconfig/core/util/CommonUtil.java
> Fix check on IBAN validity and due dates

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- openapi/swagger.json
- pom.xml
- src/main/java/it/gov/pagopa/apiconfig/core/controller/StationsController.java
- src/main/java/it/gov/pagopa/apiconfig/core/service/IbanService.java
- src/main/java/it/gov/pagopa/apiconfig/core/service/StationsService.java
- src/main/java/it/gov/pagopa/apiconfig/core/specification/PaStazionePaSpecification.java
- src/test/java/it/gov/pagopa/apiconfig/TestUtil.java
- src/test/java/it/gov/pagopa/apiconfig/core/service/IbanServiceTest.java
- src/test/java/it/gov/pagopa/apiconfig/core/service/StationsServiceTest.java
- src/test/java/it/gov/pagopa/apiconfig/core/specification/PaStazionePaSpecificationTest.java
> feat: minor bug-fixing on IBAN update and added  new filter for stations

- openapi/openapi.json
- openapi/swagger.json
- src/main/java/it/gov/pagopa/apiconfig/core/model/psp/ChannelPsp.java
- src/main/java/it/gov/pagopa/apiconfig/core/service/ChannelsService.java
- added PSP tax code to getChannelPaymentServiceProviders API response
- updated openapi
> [PAGOPA-1558] feat: Add PSP tax code to get channel psp API 

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
Update `proxyBodySize` to 4MB in all environment helm values
In order to upload `CBILL` file it is required to increase the proxy body size of the ingress
> ci(helm): Update proxy body size value

- openapi/openapi.json
- src/main/java/it/gov/pagopa/apiconfig/core/controller/StationMaintenanceController.java
- src/main/java/it/gov/pagopa/apiconfig/core/exception/AppError.java
- src/main/java/it/gov/pagopa/apiconfig/core/repository/ExtendedStationMaintenanceRepository.java
- src/main/java/it/gov/pagopa/apiconfig/core/service/StationMaintenanceService.java
- src/test/java/it/gov/pagopa/apiconfig/core/service/StationMaintenanceServiceTest.java
- fixed get maintenance summary API in order to return a default summary when no summary is found on DB
- fixed get maintenance detail API
- updated openapi and unit tests
> fix: Maintenance API

- openapi/openapi.json
- src/main/java/it/gov/pagopa/apiconfig/core/controller/StationMaintenanceController.java
- src/main/java/it/gov/pagopa/apiconfig/core/model/stationmaintenance/CreateStationMaintenance.java
- src/main/java/it/gov/pagopa/apiconfig/core/model/stationmaintenance/StationMaintenanceResource.java
- src/main/java/it/gov/pagopa/apiconfig/core/model/stationmaintenance/UpdateStationMaintenance.java
- src/main/java/it/gov/pagopa/apiconfig/core/util/Constants.java
- add offset to date format and examples
- updated openapi
> fix: Date format

- pom.xml
> fix: bump api config starter version

- .github/workflows/deploy_with_github_runner.yml
- .github/workflows/release_deploy.yml
- .identity/00_data.tf
- .identity/03_github_environment.tf
- .identity/99_main.tf
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- openapi/swagger.json
- pom.xml
Adding deploy with workload identity and upgrade to helm 7.5.0
Needed in order to upgrade helm and use the new workload identity
Manually
> Pidm 487 wl identity helm 7 5 0
